GET http://127.0.0.1:8000/products/ HTTP/1.1

###

GET http://127.0.0.1:8000/products/2/ HTTP/1.1

###

DELETE http://127.0.0.1:8000/products/2/ HTTP/1.1

###

PUT http://127.0.0.1:8000/products/1/ HTTP/1.1
Content-Type: application/json

{
    "name": "Television 2",
    "price": 322.00,
    "stock": 20,
    "description": "An amazing new TV 2"
}

###

POST http://127.0.0.1:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer _____

{
    "name": "Television",
    "price": -300.00,
    "stock": 14,
    "description": "An amazing new TV"
}

###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

###

GET http://127.0.0.1:8000/user-orders/ HTTP/1.1
Authorization: Bearer _____

###

GET http://127.0.0.1:8000/orders/ HTTP/1.1
Authorization: Bearer _____

###

GET http://127.0.0.1:8000/orders/b1a066b9-897f-4ab2-930d-37b8b4371a8a HTTP/1.1
Authorization: Bearer _____

###

POST http://127.0.0.1:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer _____

{
    "status": "Pending",
    "items": [
        {
            "product": 2,
            "quantity": 2
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

###

PUT http://127.0.0.1:8000/orders/b1a066b9-897f-4ab2-930d-37b8b4371a8a/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer _____

{
    "status": "Pending",
    "items": [
        {
            "product": 2,
            "quantity": 8
        },
        {
            "product": 3,
            "quantity": 1
        }
    ]
}

###

DELETE http://127.0.0.1:8000/orders/b1a066b9-897f-4ab2-930d-37b8b4371a8a/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer _____